import rejig.pybytecode
from rejig.syntaxtree import *

def check(what_is, what_should_be):
    env = {}
    if "\n" in what_is or "=" in what_is:
        exec("def f():\n    " + "\n    ".join(what_is.split("\n")), env)
    else:
        exec("def f():\n    return " + what_is, env)
    ast = rejig.pybytecode.ast(env["f"])
    print(str(ast))
    if what_should_be is None:
        raise NotImplementedError(repr(ast))
    assert ast == what_should_be, repr(ast)

check('"hello"', Suite((Call('return', Const('hello')),)))
check('''.3''', Suite((Call('return', Const(.3)),)))
check('''-3''', Suite((Call('return', Const(-3)),)))
check('''--3''', Suite((Call('return', Const(--3)),)))
check('''+3''', Suite((Call('return', Const(+3)),)))
check('''++3''', Suite((Call('return', Const(++3)),)))
check('''+-3''', Suite((Call('return', Const(+-3)),)))
check('''3e1''', Suite((Call('return', Const(3e1)),)))
check('''-3e1''', Suite((Call('return', Const(-3e1)),)))
check('''+3e1''', Suite((Call('return', Const(+3e1)),)))
check('0x123', Suite((Call('return', Const(0x123)),)))
check('0o123', Suite((Call('return', Const(0o123)),)))
check('3+4j', Suite((Call('return', Const(3+4j)),)))

check('''[]''', Suite((Call('return', Call('list')),)))
check('''[3]''', Suite((Call('return', Call('list', Const(3))),)))
check('''[3,]''', Suite((Call('return', Call('list', Const(3))),)))
check('''[3, 4]''', Suite((Call('return', Call('list', Const(3), Const(4))),)))
check('''[3, 4,]''', Suite((Call('return', Call('list', Const(3), Const(4))),)))
check('''[3, 4, 5]''', Suite((Call('return', Call('list', Const(3), Const(4), Const(5))),)))
check('''[3, 4, 5,]''', Suite((Call('return', Call('list', Const(3), Const(4), Const(5))),)))
check('''[3, 4, 5, 6]''', Suite((Call('return', Call('list', Const(3), Const(4), Const(5), Const(6))),)))
check('''[3, 4, 5, 6,]''', Suite((Call('return', Call('list', Const(3), Const(4), Const(5), Const(6))),)))

check('''[[1], 2, 3, 4, 5]''', Suite((Call('return', Call('list', Call('list', Const(1)), Const(2), Const(3), Const(4), Const(5))),)))
check('''[[1, 2], 3, 4, 5]''', Suite((Call('return', Call('list', Call('list', Const(1), Const(2)), Const(3), Const(4), Const(5))),)))
check('''[[1, 2, 3], 4, 5]''', Suite((Call('return', Call('list', Call('list', Const(1), Const(2), Const(3)), Const(4), Const(5))),)))
check('''[[1, 2, 3, 4], 5]''', Suite((Call('return', Call('list', Call('list', Const(1), Const(2), Const(3), Const(4)), Const(5))),)))
check('''[[1, 2, 3, 4, 5]]''', Suite((Call('return', Call('list', Call('list', Const(1), Const(2), Const(3), Const(4), Const(5)))),)))
check('''[[[1], 2, 3, 4, 5]]''', Suite((Call('return', Call('list', Call('list', Call('list', Const(1)), Const(2), Const(3), Const(4), Const(5)))),)))
check('''[[[1, 2], 3, 4, 5]]''', Suite((Call('return', Call('list', Call('list', Call('list', Const(1), Const(2)), Const(3), Const(4), Const(5)))),)))
check('''[[[1, 2, 3], 4, 5]]''', Suite((Call('return', Call('list', Call('list', Call('list', Const(1), Const(2), Const(3)), Const(4), Const(5)))),)))
check('''[[[1, 2, 3, 4], 5]]''', Suite((Call('return', Call('list', Call('list', Call('list', Const(1), Const(2), Const(3), Const(4)), Const(5)))),)))
check('''[[[1, 2, 3, 4, 5]]]''', Suite((Call('return', Call('list', Call('list', Call('list', Const(1), Const(2), Const(3), Const(4), Const(5))))),)))

check('''[1, 2, 3, 4, [5]]''', Suite((Call('return', Call('list', Const(1), Const(2), Const(3), Const(4), Call('list', Const(5)))),)))
check('''[1, 2, 3, [4, 5]]''', Suite((Call('return', Call('list', Const(1), Const(2), Const(3), Call('list', Const(4), Const(5)))),)))
check('''[1, 2, [3, 4, 5]]''', Suite((Call('return', Call('list', Const(1), Const(2), Call('list', Const(3), Const(4), Const(5)))),)))
check('''[1, [2, 3, 4, 5]]''', Suite((Call('return', Call('list', Const(1), Call('list', Const(2), Const(3), Const(4), Const(5)))),)))
check('''[[1, 2, 3, 4, [5]]]''', Suite((Call('return', Call('list', Call('list', Const(1), Const(2), Const(3), Const(4), Call('list', Const(5))))),)))
check('''[[1, 2, 3, [4, 5]]]''', Suite((Call('return', Call('list', Call('list', Const(1), Const(2), Const(3), Call('list', Const(4), Const(5))))),)))
check('''[[1, 2, [3, 4, 5]]]''', Suite((Call('return', Call('list', Call('list', Const(1), Const(2), Call('list', Const(3), Const(4), Const(5))))),)))
check('''[[1, [2, 3, 4, 5]]]''', Suite((Call('return', Call('list', Call('list', Const(1), Call('list', Const(2), Const(3), Const(4), Const(5))))),)))

check('''x = (None)''', Suite((Assign((Name('x'),), Const(None)), Call('return', Const(None)),)))
check('''x = (3, None)''', Suite((Assign((Name('x'),), Call('tuple', Const(3), Const(None))), Call('return', Const(None)),)))
check('''x = (3, 4, None)''', Suite((Assign((Name('x'),), Call('tuple', Const(3), Const(4), Const(None))), Call('return', Const(None)),)))
check('''x = (3, 4, 5, None)''', Suite((Assign((Name('x'),), Call('tuple', Const(3), Const(4), Const(5), Const(None))), Call('return', Const(None)),)))
check('''x = (3, 4, 5, 6, None)''', Suite((Assign((Name('x'),), Call('tuple', Const(3), Const(4), Const(5), Const(6), Const(None))), Call('return', Const(None)),)))

check('''x = ((1, None), 2, 3, 4, 5, None)''', Suite((Assign((Name('x'),), Call('tuple', Call('tuple', Const(1), Const(None)), Const(2), Const(3), Const(4), Const(5), Const(None))), Call('return', Const(None)),)))
check('''x = ((1, 2, None), 3, 4, 5, None)''', Suite((Assign((Name('x'),), Call('tuple', Call('tuple', Const(1), Const(2), Const(None)), Const(3), Const(4), Const(5), Const(None))), Call('return', Const(None)),)))
check('''x = ((1, 2, 3, None), 4, 5, None)''', Suite((Assign((Name('x'),), Call('tuple', Call('tuple', Const(1), Const(2), Const(3), Const(None)), Const(4), Const(5), Const(None))), Call('return', Const(None)),)))
check('''x = ((1, 2, 3, 4, None), 5, None)''', Suite((Assign((Name('x'),), Call('tuple', Call('tuple', Const(1), Const(2), Const(3), Const(4), Const(None)), Const(5), Const(None))), Call('return', Const(None)),)))
check('''x = ((1, 2, 3, 4, 5, None), None)''', Suite((Assign((Name('x'),), Call('tuple', Call('tuple', Const(1), Const(2), Const(3), Const(4), Const(5), Const(None)), Const(None))), Call('return', Const(None)),)))
check('''x = (((1, None), 2, 3, 4, 5, None), None)''', Suite((Assign((Name('x'),), Call('tuple', Call('tuple', Call('tuple', Const(1), Const(None)), Const(2), Const(3), Const(4), Const(5), Const(None)), Const(None))), Call('return', Const(None)),)))
check('''x = (((1, 2, None), 3, 4, 5, None), None)''', Suite((Assign((Name('x'),), Call('tuple', Call('tuple', Call('tuple', Const(1), Const(2), Const(None)), Const(3), Const(4), Const(5), Const(None)), Const(None))), Call('return', Const(None)),)))
check('''x = (((1, 2, 3, None), 4, 5, None), None)''', Suite((Assign((Name('x'),), Call('tuple', Call('tuple', Call('tuple', Const(1), Const(2), Const(3), Const(None)), Const(4), Const(5), Const(None)), Const(None))), Call('return', Const(None)),)))
check('''x = (((1, 2, 3, 4, None), 5, None), None)''', Suite((Assign((Name('x'),), Call('tuple', Call('tuple', Call('tuple', Const(1), Const(2), Const(3), Const(4), Const(None)), Const(5), Const(None)), Const(None))), Call('return', Const(None)),)))
check('''x = (((1, 2, 3, 4, 5, None), None), None)''', Suite((Assign((Name('x'),), Call('tuple', Call('tuple', Call('tuple', Const(1), Const(2), Const(3), Const(4), Const(5), Const(None)), Const(None)), Const(None))), Call('return', Const(None)),)))

check('''x = (1, 2, 3, 4, (5, None), None)''', Suite((Assign((Name('x'),), Call('tuple', Const(1), Const(2), Const(3), Const(4), Call('tuple', Const(5), Const(None)), Const(None))), Call('return', Const(None)),)))
check('''x = (1, 2, 3, (4, 5, None), None)''', Suite((Assign((Name('x'),), Call('tuple', Const(1), Const(2), Const(3), Call('tuple', Const(4), Const(5), Const(None)), Const(None))), Call('return', Const(None)),)))
check('''x = (1, 2, (3, 4, 5, None), None)''', Suite((Assign((Name('x'),), Call('tuple', Const(1), Const(2), Call('tuple', Const(3), Const(4), Const(5), Const(None)), Const(None))), Call('return', Const(None)),)))
check('''x = (1, (2, 3, 4, 5, None), None)''', Suite((Assign((Name('x'),), Call('tuple', Const(1), Call('tuple', Const(2), Const(3), Const(4), Const(5), Const(None)), Const(None))), Call('return', Const(None)),)))
check('''x = ((1, 2, 3, 4, (5, None), None), None)''', Suite((Assign((Name('x'),), Call('tuple', Call('tuple', Const(1), Const(2), Const(3), Const(4), Call('tuple', Const(5), Const(None)), Const(None)), Const(None))), Call('return', Const(None)),)))
check('''x = ((1, 2, 3, (4, 5, None), None), None)''', Suite((Assign((Name('x'),), Call('tuple', Call('tuple', Const(1), Const(2), Const(3), Call('tuple', Const(4), Const(5), Const(None)), Const(None)), Const(None))), Call('return', Const(None)),)))
check('''x = ((1, 2, (3, 4, 5, None), None), None)''', Suite((Assign((Name('x'),), Call('tuple', Call('tuple', Const(1), Const(2), Call('tuple', Const(3), Const(4), Const(5), Const(None)), Const(None)), Const(None))), Call('return', Const(None)),)))
check('''x = ((1, (2, 3, 4, 5, None), None), None)''', Suite((Assign((Name('x'),), Call('tuple', Call('tuple', Const(1), Call('tuple', Const(2), Const(3), Const(4), Const(5), Const(None)), Const(None)), Const(None))), Call('return', Const(None)),)))

check('''3
    ''', Suite((Call('return', Const(None)),)))   # hey look: Python does dead code removal!
check('''3
    ''', Suite((Call('return', Const(None)),)))
check('''3
    ''', Suite((Call('return', Const(None)),)))
check('''3
    ''', Suite((Call('return', Const(None)),)))
check('''
3''', Suite((Call('return', Const(None)),)))
check('''
3''', Suite((Call('return', Const(None)),)))
check('''
3''', Suite((Call('return', Const(None)),)))
check('''
3''', Suite((Call('return', Const(None)),)))

check('''a''', Suite((Call('return', Name('a')),)))
check('''a.b''', Suite((Call('return', Call('.', Name('a'), 'b')),)))
check('''a.b.c''', Suite((Call('return', Call('.', Call('.', Name('a'), 'b'), 'c')),)))
check('''a.b.c.d''', Suite((Call('return', Call('.', Call('.', Call('.', Name('a'), 'b'), 'c'), 'd')),)))
check('''a.b.c.d.e''', Suite((Call('return', Call('.', Call('.', Call('.', Call('.', Name('a'), 'b'), 'c'), 'd'), 'e')),)))
check('''a[1]''', Suite((Call('return', Call('[.]', Name('a'), Const(1))),)))
check('''a[1][2]''', Suite((Call('return', Call('[.]', Call('[.]', Name('a'), Const(1)), Const(2))),)))
check('''a[1][2][3]''', Suite((Call('return', Call('[.]', Call('[.]', Call('[.]', Name('a'), Const(1)), Const(2)), Const(3))),)))
check('''a[1][2][3][4]''', Suite((Call('return', Call('[.]', Call('[.]', Call('[.]', Call('[.]', Name('a'), Const(1)), Const(2)), Const(3)), Const(4))),)))
check('''(9, None).stuff''', Suite((Call('return', Call('.', Call('tuple', Const(9), Const(None)), 'stuff')),)))
check('''((9, None), None).stuff''', Suite((Call('return', Call('.', Call('tuple', Call('tuple', Const(9), Const(None)), Const(None)), 'stuff')),)))
check('''(((9, None), None), None).stuff''', Suite((Call('return', Call('.', Call('tuple', Call('tuple', Call('tuple', Const(9), Const(None)), Const(None)), Const(None)), 'stuff')),)))

check('''a[1]''', Suite((Call('return', Call('[.]', Name('a'), Const(1))),)))
check('''a["hey"]''', Suite((Call('return', Call('[.]', Name('a'), Const('hey'))),)))
check('''a[1:2]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(2), Const(None)))),)))
check('''a[:]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(None), Const(None)))),)))
check('''a[1:]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(None), Const(None)))),)))
check('''a[:1]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(1), Const(None)))),)))
check('''a[::]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(None), Const(None)))),)))
check('''a[1::]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(None), Const(None)))),)))
check('''a[:1:]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(1), Const(None)))),)))
check('''a[::1]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(None), Const(1)))),)))
check('''a[1:2:]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(2), Const(None)))),)))
check('''a[:1:2]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(1), Const(2)))),)))
check('''a[1::2]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(None), Const(2)))),)))
check('''a[1:2:3]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(2), Const(3)))),)))
check('''a[1,]''', Suite((Call('return', Call('[.]', Name('a'), Const(1))),)))
check('''a["hey",]''', Suite((Call('return', Call('[.]', Name('a'), Const('hey'))),)))
check('''a[1:2,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(2), Const(None)))),)))
check('''a[:,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(None), Const(None)))),)))
check('''a[1:,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(None), Const(None)))),)))
check('''a[:1,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(1), Const(None)))),)))
check('''a[::,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(None), Const(None)))),)))
check('''a[1::,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(None), Const(None)))),)))
check('''a[:1:,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(1), Const(None)))),)))
check('''a[::1,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(None), Const(1)))),)))
check('''a[1:2:,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(2), Const(None)))),)))
check('''a[:1:2,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(1), Const(2)))),)))
check('''a[1::2,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(None), Const(2)))),)))
check('''a[1:2:3,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(2), Const(3)))),)))
check('''a[1,5]''', Suite((Call('return', Call('[.]', Name('a'), Const(1), Const(5))),)))
check('''a["hey",5]''', Suite((Call('return', Call('[.]', Name('a'), Const('hey'), Const(5))),)))
check('''a[1:2,5]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(2), Const(None)), Const(5))),)))
check('''a[:,5]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(None), Const(None)), Const(5))),)))
check('''a[1:,5]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(None), Const(None)), Const(5))),)))
check('''a[:1,5]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(1), Const(None)), Const(5))),)))
check('''a[::,5]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(None), Const(None)), Const(5))),)))
check('''a[1::,5]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(None), Const(None)), Const(5))),)))
check('''a[:1:,5]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(1), Const(None)), Const(5))),)))
check('''a[::1,5]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(None), Const(1)), Const(5))),)))
check('''a[1:2:,5]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(2), Const(None)), Const(5))),)))
check('''a[:1:2,5]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(1), Const(2)), Const(5))),)))
check('''a[1::2,5]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(None), Const(2)), Const(5))),)))
check('''a[1:2:3,5]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(2), Const(3)), Const(5))),)))
check('''a[1,5,]''', Suite((Call('return', Call('[.]', Name('a'), Const(1), Const(5))),)))
check('''a["hey",5,]''', Suite((Call('return', Call('[.]', Name('a'), Const('hey'), Const(5))),)))
check('''a[1:2,5,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(2), Const(None)), Const(5))),)))
check('''a[:,5,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(None), Const(None)), Const(5))),)))
check('''a[1:,5,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(None), Const(None)), Const(5))),)))
check('''a[:1,5,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(1), Const(None)), Const(5))),)))
check('''a[::,5,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(None), Const(None)), Const(5))),)))
check('''a[1::,5,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(None), Const(None)), Const(5))),)))
check('''a[:1:,5,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(1), Const(None)), Const(5))),)))
check('''a[::1,5,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(None), Const(1)), Const(5))),)))
check('''a[1:2:,5,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(2), Const(None)), Const(5))),)))
check('''a[:1:2,5,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(1), Const(2)), Const(5))),)))
check('''a[1::2,5,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(None), Const(2)), Const(5))),)))
check('''a[1:2:3,5,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(2), Const(3)), Const(5))),)))
check('''a[1,"a":"b"]''', Suite((Call('return', Call('[.]', Name('a'), Const(1), Call('slice', Const('a'), Const('b'), Const(None)))),)))
check('''a["hey","a":"b"]''', Suite((Call('return', Call('[.]', Name('a'), Const('hey'), Call('slice', Const('a'), Const('b'), Const(None)))),)))
check('''a[1:2,"a":"b"]''', Suite((Call('return', Call('[.]', Name('a'), Call("slice", Const(1), Const(2), Const(None)), Call('slice', Const('a'), Const('b'), Const(None)))),)))
check('''a[:,"a":"b"]''', Suite((Call('return', Call('[.]', Name('a'), Call("slice", Const(None), Const(None), Const(None)), Call('slice', Const('a'), Const('b'), Const(None)))),)))
check('''a[1:,"a":"b"]''', Suite((Call('return', Call('[.]', Name('a'), Call("slice", Const(1), Const(None), Const(None)), Call('slice', Const('a'), Const('b'), Const(None)))),)))
check('''a[:1,"a":"b"]''', Suite((Call('return', Call('[.]', Name('a'), Call("slice", Const(None), Const(1), Const(None)), Call('slice', Const('a'), Const('b'), Const(None)))),)))
check('''a[::,"a":"b"]''', Suite((Call('return', Call('[.]', Name('a'), Call("slice", Const(None), Const(None), Const(None)), Call('slice', Const('a'), Const('b'), Const(None)))),)))
check('''a[1::,"a":"b"]''', Suite((Call('return', Call('[.]', Name('a'), Call("slice", Const(1), Const(None), Const(None)), Call('slice', Const('a'), Const('b'), Const(None)))),)))
check('''a[:1:,"a":"b"]''', Suite((Call('return', Call('[.]', Name('a'), Call("slice", Const(None), Const(1), Const(None)), Call('slice', Const('a'), Const('b'), Const(None)))),)))
check('''a[::1,"a":"b"]''', Suite((Call('return', Call('[.]', Name('a'), Call("slice", Const(None), Const(None), Const(1)), Call('slice', Const('a'), Const('b'), Const(None)))),)))
check('''a[1:2:,"a":"b"]''', Suite((Call('return', Call('[.]', Name('a'), Call("slice", Const(1), Const(2), Const(None)), Call('slice', Const('a'), Const('b'), Const(None)))),)))
check('''a[:1:2,"a":"b"]''', Suite((Call('return', Call('[.]', Name('a'), Call("slice", Const(None), Const(1), Const(2)), Call('slice', Const('a'), Const('b'), Const(None)))),)))
check('''a[1::2,"a":"b"]''', Suite((Call('return', Call('[.]', Name('a'), Call("slice", Const(1), Const(None), Const(2)), Call('slice', Const('a'), Const('b'), Const(None)))),)))
check('''a[1:2:3,"a":"b"]''', Suite((Call('return', Call('[.]', Name('a'), Call("slice", Const(1), Const(2), Const(3)), Call('slice', Const('a'), Const('b'), Const(None)))),)))
check('''a[1,"a":"b",]''', Suite((Call('return', Call('[.]', Name('a'), Const(1), Call('slice', Const('a'), Const('b'), Const(None)))),)))
check('''a["hey","a":"b",]''', Suite((Call('return', Call('[.]', Name('a'), Const('hey'), Call('slice', Const('a'), Const('b'), Const(None)))),)))
check('''a[1:2,"a":"b",]''', Suite((Call('return', Call('[.]', Name('a'), Call("slice", Const(1), Const(2), Const(None)), Call('slice', Const('a'), Const('b'), Const(None)))),)))
check('''a[:,"a":"b",]''', Suite((Call('return', Call('[.]', Name('a'), Call("slice", Const(None), Const(None), Const(None)), Call('slice', Const('a'), Const('b'), Const(None)))),)))
check('''a[1:,"a":"b",]''', Suite((Call('return', Call('[.]', Name('a'), Call("slice", Const(1), Const(None), Const(None)), Call('slice', Const('a'), Const('b'), Const(None)))),)))
check('''a[:1,"a":"b",]''', Suite((Call('return', Call('[.]', Name('a'), Call("slice", Const(None), Const(1), Const(None)), Call('slice', Const('a'), Const('b'), Const(None)))),)))
check('''a[::,"a":"b",]''', Suite((Call('return', Call('[.]', Name('a'), Call("slice", Const(None), Const(None), Const(None)), Call('slice', Const('a'), Const('b'), Const(None)))),)))
check('''a[1::,"a":"b",]''', Suite((Call('return', Call('[.]', Name('a'), Call("slice", Const(1), Const(None), Const(None)), Call('slice', Const('a'), Const('b'), Const(None)))),)))
check('''a[:1:,"a":"b",]''', Suite((Call('return', Call('[.]', Name('a'), Call("slice", Const(None), Const(1), Const(None)), Call('slice', Const('a'), Const('b'), Const(None)))),)))
check('''a[::1,"a":"b",]''', Suite((Call('return', Call('[.]', Name('a'), Call("slice", Const(None), Const(None), Const(1)), Call('slice', Const('a'), Const('b'), Const(None)))),)))
check('''a[1:2:,"a":"b",]''', Suite((Call('return', Call('[.]', Name('a'), Call("slice", Const(1), Const(2), Const(None)), Call('slice', Const('a'), Const('b'), Const(None)))),)))
check('''a[:1:2,"a":"b",]''', Suite((Call('return', Call('[.]', Name('a'), Call("slice", Const(None), Const(1), Const(2)), Call('slice', Const('a'), Const('b'), Const(None)))),)))
check('''a[1::2,"a":"b",]''', Suite((Call('return', Call('[.]', Name('a'), Call("slice", Const(1), Const(None), Const(2)), Call('slice', Const('a'), Const('b'), Const(None)))),)))
check('''a[1:2:3,"a":"b",]''', Suite((Call('return', Call('[.]', Name('a'), Call("slice", Const(1), Const(2), Const(3)), Call('slice', Const('a'), Const('b'), Const(None)))),)))
check('''a[1,5,6]''', Suite((Call('return', Call('[.]', Name('a'), Const(1), Const(5), Const(6))),)))
check('''a["hey",5,6]''', Suite((Call('return', Call('[.]', Name('a'), Const('hey'), Const(5), Const(6))),)))
check('''a[1:2,5,6]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(2), Const(None)), Const(5), Const(6))),)))
check('''a[:,5,6]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(None), Const(None)), Const(5), Const(6))),)))
check('''a[1:,5,6]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(None), Const(None)), Const(5), Const(6))),)))
check('''a[:1,5,6]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(1), Const(None)), Const(5), Const(6))),)))
check('''a[::,5,6]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(None), Const(None)), Const(5), Const(6))),)))
check('''a[1::,5,6]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(None), Const(None)), Const(5), Const(6))),)))
check('''a[:1:,5,6]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(1), Const(None)), Const(5), Const(6))),)))
check('''a[::1,5,6]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(None), Const(1)), Const(5), Const(6))),)))
check('''a[1:2:,5,6]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(2), Const(None)), Const(5), Const(6))),)))
check('''a[:1:2,5,6]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(1), Const(2)), Const(5), Const(6))),)))
check('''a[1::2,5,6]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(None), Const(2)), Const(5), Const(6))),)))
check('''a[1:2:3,5,6]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(2), Const(3)), Const(5), Const(6))),)))
check('''a[1,5,6,]''', Suite((Call('return', Call('[.]', Name('a'), Const(1), Const(5), Const(6))),)))
check('''a["hey",5,6,]''', Suite((Call('return', Call('[.]', Name('a'), Const('hey'), Const(5), Const(6))),)))
check('''a[1:2,5,6,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(2), Const(None)), Const(5), Const(6))),)))
check('''a[:,5,6,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(None), Const(None)), Const(5), Const(6))),)))
check('''a[1:,5,6,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(None), Const(None)), Const(5), Const(6))),)))
check('''a[:1,5,6,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(1), Const(None)), Const(5), Const(6))),)))
check('''a[::,5,6,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(None), Const(None)), Const(5), Const(6))),)))
check('''a[1::,5,6,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(None), Const(None)), Const(5), Const(6))),)))
check('''a[:1:,5,6,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(1), Const(None)), Const(5), Const(6))),)))
check('''a[::1,5,6,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(None), Const(1)), Const(5), Const(6))),)))
check('''a[1:2:,5,6,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(2), Const(None)), Const(5), Const(6))),)))
check('''a[:1:2,5,6,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(None), Const(1), Const(2)), Const(5), Const(6))),)))
check('''a[1::2,5,6,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(None), Const(2)), Const(5), Const(6))),)))
check('''a[1:2:3,5,6,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Const(2), Const(3)), Const(5), Const(6))),)))
check('''a[1:[2]:3,[],5,6,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Call('list', Const(2)), Const(3)), Call('list'), Const(5), Const(6))),)))
check('''a[1:[[2]]:3,[[]],5,6,]''', Suite((Call('return', Call('[.]', Name('a'), Call('slice', Const(1), Call('list', Call('list', Const(2))), Const(3)), Call('list', Call('list')), Const(5), Const(6))),)))

check('''a[2].three''', Suite((Call('return', Call('.', Call('[.]', Name('a'), Const(2)), 'three')),)))
check('''a.three''', Suite((Call('return', Call('.', Name('a'), 'three')),)))
check('''a[2]''', Suite((Call('return', Call('[.]', Name('a'), Const(2))),)))
check('''a.three[2]''', Suite((Call('return', Call('[.]', Call('.', Name('a'), 'three'), Const(2))),)))

check('''x and y''', None)
check('''x and y and z''', None)
check('''x and y and z and w''', None)
check('''not x''', None)
check('''not x and y''', None)
check('''x or y''', None)
check('''x or y and z''', None)
check('''x or y or z''', None)
check('''not x or y and z''', None)
check('''x or not y and z''', None)
check('''x or y and not z''', None)
check('''not x or not y and z''', None)
check('''not x or y and not z''', None)
check('''x or not y and not z''', None)
check('''not x or not y and not z''', None)
check('''x and y or z''', None)
check('''not x and y or z''', None)
check('''x and not y or z''', None)
check('''x and y or not z''', None)
check('''not x and not y or z''', None)
check('''not x and y or not z''', None)
check('''x and not y or not z''', None)

check('''x < y''', None)
check('''x > y''', None)
check('''x == y''', None)
check('''x >= y''', None)
check('''x <= y''', None)
check('''x != y''', None)
check('''x in y''', None)
check('''x not in y''', None)
check('''1 < y < 2''', None)
check('''1 < y == 2''', None)

check('''(x, None) < y''', None)
check('''(x, None) > y''', None)
check('''(x, None) == y''', None)
check('''(x, None) >= y''', None)
check('''(x, None) <= y''', None)
check('''(x, None) != y''', None)
check('''(x, None) in y''', None)
check('''(x, None) not in y''', None)
check('''(1, None) < y < 2''', None)
check('''(1, None) < y == 2''', None)

check('''x < (y, None)''', None)
check('''x > (y, None)''', None)
check('''x == (y, None)''', None)
check('''x >= (y, None)''', None)
check('''x <= (y, None)''', None)
check('''x != (y, None)''', None)
check('''x in (y, None)''', None)
check('''x not in (y, None)''', None)
check('''1 < (y, None) < 2''', None)
check('''1 < (y, None) == 2''', None)
check('''1 < y < (2, None)''', None)
check('''1 < y == (2, None)''', None)

check('''(x, None) < (y, None)''', None)
check('''(x, None) > (y, None)''', None)
check('''(x, None) == (y, None)''', None)
check('''(x, None) >= (y, None)''', None)
check('''(x, None) <= (y, None)''', None)
check('''(x, None) != (y, None)''', None)
check('''(x, None) in (y, None)''', None)
check('''(x, None) not in (y, None)''', None)
check('''(1, None) < (y, None) < 2''', None)
check('''(1, None) < (y, None) == 2''', None)
check('''(1, None) < y < (2, None)''', None)
check('''(1, None) < y == (2, None)''', None)

check('''x + y''', None)
check('''x + y + z''', None)
check('''x + y + z + w''', None)
check('''x - y''', None)
check('''x - y - z''', None)
check('''x - y - z - w''', None)
check('''x - y + z - w''', None)
check('''x * y''', None)
check('''x * y * z''', None)
check('''x * y * z * w''', None)
check('''x * y - z * w''', None)
check('''x / y''', None)
check('''x / y / z''', None)
check('''x / y / z / w''', None)
check('''x / y * z / w''', None)
check('''x % y''', None)
check('''x % y % z''', None)
check('''x % y % z % w''', None)
check('''x % y / z % w''', None)
check('''x // y''', None)
check('''x // y // z''', None)
check('''x // y // z // w''', None)
check('''x // y % z // w''', None)
check('''+x''', None)
check('''-x''', None)
check('''++x''', None)
check('''+-x''', None)
check('''-+x''', None)
check('''--x''', None)
check('''+x + y''', None)
check('''-x + y''', None)
check('''++x + y''', None)
check('''+-x + y''', None)
check('''-+x + y''', None)
check('''--x + y''', None)
check('''x + +x''', None)
check('''x + -x''', None)
check('''x + ++x''', None)
check('''x + +-x''', None)
check('''x + -+x''', None)
check('''x + --x''', None)
check('''x ** y''', None)
check('''x ** y ** z''', None)
check('''x ** y ** z ** w''', None)
check('''x ** y // z ** w''', None)
check('''x.y**2''', None)

check('f(, None)', None)
check('f(x, None)', None)
check('f(x,, None)', None)
check('f(x, y, None)', None)
check('f(x, y,, None)', None)
check('f(x, y, z, None)', None)
check('f(x, y, z,, None)', None)
check('f(x=1, None)', None)
check('f(x=1,, None)', None)
check('f(x, y=1, None)', None)
check('f(x, y=1,, None)', None)
check('f(x, y, z=1, None)', None)

check('x = 1; x', None)

check('x = 1; x', None)
check('x = 1; x;', None)
check('x, = 1; x', None)
check('x, y = 1; x', None)
check('x, y, = 1; x', None)
check('x, y, z = 1; x', None)
check('x, y, z, = 1; x', None)

check("False", None)
check("True", None)
check("not x", None)
check("not x and not y", None)
check("not x and not y and not z", None)
check("not x and not y and not z", None)
check("not x and not y and not z", None)
check("not x or not y", None)
check("not x or not y or not z", None)
check("not x or not y or not z", None)
check("not x or not y or not z", None)
check("(not x or not y, None) and not z", None)
check("not x and (not y or not z, None)", None)

check("not x(1, None)", None)
check("not x(1, None) and not y(2, None)", None)
check("not x(1, None) and not y(2, None) and not z(3, None)", None)
check("not x(1, None) and not y(2, None) and not z(3, None)", None)
check("not x(1, None) and not y(2, None) and not z(3, None)", None)
check("not x(1, None) or not y(2, None)", None)
check("not x(1, None) or not y(2, None) or not z(3, None)", None)
check("not x(1, None) or not y(2, None) or not z(3, None)", None)
check("not x(1, None) or not y(2, None) or not z(3, None)", None)
check("(not x(1, None) or not y(2, None), None) and not z(3, None)", None)
check("not x(1, None) and (not y(2, None) or not z(3, None), None)", None)

check("not x.a", None)
check("not x.a and not y.b", None)
check("not x.a and not y.b and not z.c", None)
check("not x.a and not y.b and not z.c", None)
check("not x.a and not y.b and not z.c", None)
check("not x.a or not y.b", None)
check("not x.a or not y.b or not z.c", None)
check("not x.a or not y.b or not z.c", None)
check("not x.a or not y.b or not z.c", None)
check("(not x.a or not y.b, None) and not z.c", None)
check("not x.a and (not y.b or not z.c, None)", None)

check("False", None)
check("True", None)
check("not x", None)
check("not x and not y", None)
check("not x and not y and not z", None)
check("not x and not y and not z", None)
check("not x and not y and not z", None)
check("not x or not y", None)
check("not x or not y or not z", None)
check("not x or not y or not z", None)
check("not x or not y or not z", None)
check("(not x or not y, None) and not z", None)
check("not x and (not y or not z, None)", None)

check("not x(1, None)", None)
check("not x(1, None) and not y(2, None)", None)
check("not x(1, None) and not y(2, None) and not z(3, None)", None)
check("not x(1, None) and not y(2, None) and not z(3, None)", None)
check("not x(1, None) and not y(2, None) and not z(3, None)", None)
check("not x(1, None) or not y(2, None)", None)
check("not x(1, None) or not y(2, None) or not z(3, None)", None)
check("not x(1, None) or not y(2, None) or not z(3, None)", None)
check("not x(1, None) or not y(2, None) or not z(3, None)", None)
check("(not x(1, None) or not y(2, None), None) and not z(3, None)", None)
check("not x(1, None) and (not y(2, None) or not z(3, None), None)", None)

check("not x.a", None)
check("not x.a and not y.b", None)
check("not x.a and not y.b and not z.c", None)
check("not x.a and not y.b and not z.c", None)
check("not x.a and not y.b and not z.c", None)
check("not x.a or not y.b", None)
check("not x.a or not y.b or not z.c", None)
check("not x.a or not y.b or not z.c", None)
check("not x.a or not y.b or not z.c", None)
check("(not x.a or not y.b, None) and not z.c", None)
check("not x.a and (not y.b or not z.c, None)", None)

check("False", None)
check("True", None)
check("not x", None)
check("not x and not y", None)
check("not x and not y and not z", None)
check("not x and not y and not z", None)
check("not x and not y and not z", None)
check("not x or not y", None)
check("not x or not y or not z", None)
check("not x or not y or not z", None)
check("not x or not y or not z", None)
check("(not x or not y, None) and not z", None)
check("not x and (not y or not z, None)", None)

check("not x(1, None)", None)
check("not x(1, None) and not y(2, None)", None)
check("not x(1, None) and not y(2, None) and not z(3, None)", None)
check("not x(1, None) and not y(2, None) and not z(3, None)", None)
check("not x(1, None) and not y(2, None) and not z(3, None)", None)
check("not x(1, None) or not y(2, None)", None)
check("not x(1, None) or not y(2, None) or not z(3, None)", None)
check("not x(1, None) or not y(2, None) or not z(3, None)", None)
check("not x(1, None) or not y(2, None) or not z(3, None)", None)
check("(not x(1, None) or not y(2, None), None) and not z(3, None)", None)
check("not x(1, None) and (not y(2, None) or not z(3, None), None)", None)

check("not x.a", None)
check("not x.a and not y.b", None)
check("not x.a and not y.b and not z.c", None)
check("not x.a and not y.b and not z.c", None)
check("not x.a and not y.b and not z.c", None)
check("not x.a or not y.b", None)
check("not x.a or not y.b or not z.c", None)
check("not x.a or not y.b or not z.c", None)
check("not x.a or not y.b or not z.c", None)
check("(not x.a or not y.b, None) and not z.c", None)
check("not x.a and (not y.b or not z.c, None)", None)

check("x != y", None)
check("x == y", None)
check("x <= y", None)
check("x > y", None)
check("x >= y", None)
check("x < y", None)
check("x not in y", None)
check("x in y", None)

check("x == y and y == z", None)
check("x == y and y == z", None)
check("x == y or y == z", None)
check("x != y or y != z", None)
check("x != y or y != z", None)
check("x != y or y == z", None)

check("a and b and c and d and e", None)
check("a and b and c and d and e", None)

check("def g(, None): return 3.14", None)
check("""def g(, None):
    return 3.14""", None)
check("def g(x, None): return x**2", None)
check("""def g(x, None):
    return x**2""", None)
check("lambda: 3.14", None)
check("lambda x: x**2", None)
check("return (lambda x: x**2, None)", None)

check("1 if x == 0 else 2", None)
check("y = (1 if x == 0 else 2, None)", None)
check("1 if x == 0 else None", None)
check("return (1 if x == 0 else 2, None)", None)
check("return (1 if x == 0 else None, None)", None)
check("""if x == 0:
    return 1""", None)
check("""if x == 0:
    y = 1
    return 1""", None)
check("""if x == 0:
    return 1
else:
    return 2""", None)
check("""if x == 0:
    y = 1
    return 1
else:
    y = 2
    return 2""", None)
check("""if x == 0:
    return 1
elif x == 1:
    return 2
else:
    return 3""", None)
check("""if x == 0:
    y = 1
    return 1
elif x == 1:
    y = 2
    return 2
else:
    y = 3
    return 3""", None)
check("""if x == 0:
    y = 1""", None)
check("""if x == 0:
    y = 1
    z = 1""", None)
check("""if x == 0:
    y = 1
else:
    y = 2""", None)
check("""if x == 0:
    y = 1
    z = 1
else:
    y = 2
    z = 2""", None)
check("""if x == 0:
    y = 1
elif x == 1:
    y = 2
else:
    y = 3""", None)
check("""if x == 0:
    y = 1
    z = 1
elif x == 1:
    y = 2
    z = 2
else:
    y = 3
    z = 3""", None)
check("print(, None)", None)
check("print(1, None)", None)
check("print(1, 2, 3, None)", None)

check("[]", None)
check("[1]", None)
check("[1, 2]", None)
check("[one]", None)
check("[one, two]", None)
check("['one']", None)
check("['one', 'two']", None)
check("set([], None)", None)
check("set([1], None)", None)
check("set([1, 2], None)", None)
check("set([one], None)", None)
check("set([one, two], None)", None)
check("set(['one'], None)", None)
check("set(['one', 'two'], None)", None)
check("{}", None)
check("{1}", None)
check("{1, 2}", None)
check("{one}", None)
check("{one, two}", None)
check("{'one'}", None)
check("{'one', 'two'}", None)
check("{'x': 1}", None)
check("{'x': 1, 'y': 2}", None)
check("{'x': 1, 'y': 2, 'z': 3}", None)
check("{'x': one}", None)
check("{'x': one, 'y': two}", None)
check("{'x': one, 'y': two, 'z': three}", None)
check("{1: 1}", None)
check("{1: 1, 2: 2}", None)
check("{1: 1, 2: 2, 3: 3}", None)
check("{1: one}", None)
check("{1: one, 2: two}", None)
check("{1: one, 2: two, 3: three}", None)
check("{one: 1}", None)
check("{one: 1, two: 2}", None)
check("{one: 1, two: 2, three: 3}", None)
check("{one: one}", None)
check("{one: one, two: two}", None)
check("{one: one, two: two, three: three}", None)

check("[x**2 for x in something]", None)
check("[x**2 for x in something if x > 0]", None)
check("[y**2 for x in something for y in x]", None)
check("[y**2 for x in something for y in x if x > 0]", None)
check("[y**2 for x in something for y in x if y > 0]", None)
check("[y**2 for x in something if x for y in x if x > 0]", None)

check("f([x**2 for x in something], None)", None)
check("f([x**2 for x in something if x > 0], None)", None)
check("f([y**2 for x in something for y in x], None)", None)
check("f([y**2 for x in something for y in x if x > 0], None)", None)
check("f([y**2 for x in something for y in x if y > 0], None)", None)
check("f([y**2 for x in something if x for y in x if x > 0], None)", None)

check("f(x**2 for x in something, None)", None)
check("f(x**2 for x in something if x > 0, None)", None)
check("f(y**2 for x in something for y in x, None)", None)
check("f(y**2 for x in something for y in x if x > 0, None)", None)
check("f(y**2 for x in something for y in x if y > 0, None)", None)
check("f(y**2 for x in something if x for y in x if x > 0, None)", None)

check("f(one=1, None)", None)
check("f(one=1, two=2, None)", None)
check("f(x, one=1, None)", None)
check("f(x, one=1, two=2, None)", None)

check("x[..., :]", None)

check('x = y = 1', None)
check('x = y = z = 1', None)
check('x, y = 1', None)
check('x, y = z = 1', None)
check('x = y, z = 1', None)

check('x.a = y = 1', None)
check('x.a = y = z = 1', None)
check('x.a, y = 1', None)
check('x.a, y = z = 1', None)
check('x.a = y, z = 1', None)

check('x = y.a = 1', None)
check('x = y.a = z = 1', None)
check('x, y.a = 1', None)
check('x, y.a = z = 1', None)
check('x = y.a, z = 1', None)

check('x = y = z.a = 1', None)
check('x, y = z.a = 1', None)
check('x = y, z.a = 1', None)

check('x[0] = y = 1', None)
check('x[0] = y = z = 1', None)
check('x[0], y = 1', None)
check('x[0], y = z = 1', None)
check('x[0] = y, z = 1', None)

check('x = y[0] = 1', None)
check('x = y[0] = z = 1', None)
check('x, y[0] = 1', None)
check('x, y[0] = z = 1', None)
check('x = y[0], z = 1', None)

check('x = y = z[0] = 1', None)
check('x, y = z[0] = 1', None)
check('x = y, z[0] = 1', None)

check('x[:, ...] = y = 1', None)
check('x[:, ...] = y = z = 1', None)
check('x[:, ...], y = 1', None)
check('x[:, ...], y = z = 1', None)
check('x[:, ...] = y, z = 1', None)

check('x = y[:, ...] = 1', None)
check('x = y[:, ...] = z = 1', None)
check('x, y[:, ...] = 1', None)
check('x, y[:, ...] = z = 1', None)
check('x = y[:, ...], z = 1', None)

check('x = y = z[:, ...] = 1', None)
check('x, y = z[:, ...] = 1', None)
check('x = y, z[:, ...] = 1', None)
